name: ChimeNet CI and Docker Build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: x86_64
          - runner: [self-hosted, runner-aarch64]
            arch: aarch64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies (self-hosted Linux)
        if: runner.os == 'Linux' && contains(matrix.runner, 'self-hosted')
        run: |
          if command -v apt-get &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y pkg-config libssl-dev libasound2-dev
          elif command -v yum &> /dev/null; then
            sudo yum install -y pkgconfig openssl-devel alsa-lib-devel
          elif command -v dnf &> /dev/null; then
            sudo dnf install -y pkgconfig openssl-devel alsa-lib-devel
          elif command -v pacman &> /dev/null; then
            sudo pacman -Sy --noconfirm pkgconf openssl alsa-lib
          elif command -v apk &> /dev/null; then
            sudo apk add --no-cache pkgconfig openssl-dev alsa-lib-dev
          else
            echo "Package manager not found. Please install pkg-config, openssl-dev, and alsa-lib-dev manually."
            exit 1
          fi

      - name: Install system dependencies (GitHub-hosted Linux)
        if: runner.os == 'Linux' && !contains(matrix.runner, 'self-hosted')
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libasound2-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.86"
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      - name: Build examples
        run: |
          cargo build --bin virtual_chime --verbose
          cargo build --bin http_service --verbose
          cargo build --bin ringer_client --verbose
          cargo build --bin test_client --verbose
          cargo build --bin custom_states --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run integration tests
        run: |
          if [ -f "./test_discover.sh" ]; then
            echo "Running discovery tests..."
            # ./test_discover.sh
          fi
          if [ -f "./test_enhanced_clients.sh" ]; then
            echo "Running enhanced client tests..."
            # ./test_enhanced_clients.sh
          fi
          if [ -f "./test_ring_fix.sh" ]; then
            echo "Running ring fix tests..."
            # ./test_ring_fix.sh
          fi

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Check
        run: cargo check

      - name: Log in to the Container registry
        if: runner.os == 'Linux' && !contains(matrix.runner, 'self-hosted')
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: runner.os == 'Linux' && !contains(matrix.runner, 'self-hosted')
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        if: runner.os == 'Linux' && !contains(matrix.runner, 'self-hosted')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: chimenet-x86_64-linux-gnu.tar.gz
            archive_cmd: tar -czf
            binary_ext: ""
            rust: "1.86"
          - os: [self-hosted, runner-aarch64]
            name: chimenet-aarch64-linux-gnu.tar.gz
            archive_cmd: tar -czf
            binary_ext: ""
            rust: "1.86"
          - os: macos-latest
            name: chimenet-aarch64-macos.tar.gz
            archive_cmd: tar -czf
            binary_ext: ""
            rust: "1.86"
          - os: windows-latest
            name: chimenet-x86_64-windows.zip
            archive_cmd: 7z a
            binary_ext: ".exe"
            rust: "1.86"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies (self-hosted Linux)
        if: runner.os == 'Linux' && contains(matrix.os, 'self-hosted')
        run: |
          if command -v apt-get &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y pkg-config libssl-dev libasound2-dev
          elif command -v yum &> /dev/null; then
            sudo yum install -y pkgconfig openssl-devel alsa-lib-devel
          elif command -v dnf &> /dev/null; then
            sudo dnf install -y pkgconfig openssl-devel alsa-lib-devel
          elif command -v pacman &> /dev/null; then
            sudo pacman -Sy --noconfirm pkgconf openssl alsa-lib
          elif command -v apk &> /dev/null; then
            sudo apk add --no-cache pkgconfig openssl-dev alsa-lib-dev
          else
            echo "Package manager not found. Please install pkg-config, openssl-dev, and alsa-lib-dev manually."
            exit 1
          fi

      - name: Install system dependencies (GitHub-hosted Linux)
        if: runner.os == 'Linux' && !contains(matrix.os, 'self-hosted')
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libasound2-dev

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          # macOS typically has the required audio frameworks built-in
          echo "macOS audio dependencies should be available by default"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.rust }}

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Strip binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/release
          for binary in virtual_chime http_service ringer_client test_client custom_states; do
            if [ -f "$binary" ]; then
              strip "$binary"
              echo "Stripped $binary"
            else
              echo "Warning: Binary $binary not found"
            fi
          done

      - name: Create release archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/release
          binaries=""
          for binary in virtual_chime http_service ringer_client test_client custom_states; do
            if [ -f "$binary" ]; then
              binaries="$binaries $binary"
            fi
          done
          if [ -n "$binaries" ]; then
            tar -czf ../../${{ matrix.name }} $binaries
            echo "Created archive with binaries:$binaries"
          else
            echo "Error: No binaries found to archive"
            exit 1
          fi
          cd ../..

      - name: Create release archive (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/release
          $binaries = @()
          foreach ($binary in @("virtual_chime.exe", "http_service.exe", "ringer_client.exe", "test_client.exe", "custom_states.exe")) {
            if (Test-Path $binary) {
              $binaries += $binary
            }
          }
          if ($binaries.Count -gt 0) {
            7z a ../../${{ matrix.name }} $binaries
            Write-Host "Created archive with binaries: $($binaries -join ', ')"
          } else {
            Write-Host "Error: No binaries found to archive"
            exit 1
          }
          cd ../..

      - name: Upload release archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release notes
        run: |
          echo "# ChimeNet Release ${GITHUB_REF_NAME}" > release_notes.md
          echo "" >> release_notes.md
          echo "## Changes in this release" >> release_notes.md
          echo "" >> release_notes.md
          echo "This release includes the following binaries:" >> release_notes.md
          echo "" >> release_notes.md
          echo "- \`virtual_chime\`: Software-based chime with audio playback" >> release_notes.md
          echo "- \`http_service\`: REST API service for monitoring chime networks" >> release_notes.md
          echo "- \`ringer_client\`: Discovers and rings chimes by name" >> release_notes.md
          echo "- \`test_client\`: Testing utility for invoking chimes" >> release_notes.md
          echo "- \`custom_states\`: Advanced example with custom LCGP states" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Supported Platforms" >> release_notes.md
          echo "" >> release_notes.md
          echo "- Linux (x86_64)" >> release_notes.md
          echo "- Linux (aarch64)" >> release_notes.md
          echo "- Windows (x86_64)" >> release_notes.md
          echo "- macOS (x86_64 and Apple Silicon)" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Installation" >> release_notes.md
          echo "" >> release_notes.md
          echo "1. Download the appropriate archive for your platform" >> release_notes.md
          echo "2. Extract the binaries" >> release_notes.md
          echo "3. Place them in your PATH" >> release_notes.md
          echo "4. Setup an MQTT broker (e.g., Mosquitto)" >> release_notes.md
          echo "5. Run the components with appropriate MQTT broker configuration" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Docker Image" >> release_notes.md
          echo "" >> release_notes.md
          echo "A Docker image is also available at:" >> release_notes.md
          echo "\`\`\`" >> release_notes.md
          echo "ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME}" >> release_notes.md
          echo "\`\`\`" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Quick Start" >> release_notes.md
          echo "" >> release_notes.md
          echo "1. Start an MQTT broker: \`mosquitto\`" >> release_notes.md
          echo "2. Run a virtual chime: \`./virtual_chime --user alice --name \"Alice's Chime\"\`" >> release_notes.md
          echo "3. Run the HTTP service: \`./http_service --users alice\`" >> release_notes.md
          echo "4. Test the system: \`./test_client --target-user alice --command discover\`" >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/*.tar.gz,artifacts/*/*.zip
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
